name: old devices output *.img

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      ROM_URL:
        description: '完整包下载链接'
        required: true
        default: 'https://hugeota.d.miui.com/OS1.0.23.11.8.DEV/miui_MONDRIAN_OS1.0.23.11.8.DEV_afb8edb5c9_14.0.zip?t=1699952378&s=6b2ece88a61a438b2e2473497a48027a'
      IMG_NAME:
        description: '你要拆的分区(比如 boot/init_boot/system/product)'
        required: true
        default: 'vendor_dlkm'  
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Configuration Environment‌‌
        run: |
          sudo apt-get install -y  wget zip unzip
      
      - name: Download ROM‌‌
        run: |
          wget ${{ github.event.inputs.ROM_URL }}
      
      - name: Unzip ROM to *.img
        run: |
          unzip *.zip
      
      - name: Upload img
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.IMG_NAME }}.img
          path: ./${{ github.event.inputs.IMG_NAME }}.img
      
